name: Deploy to Firebase Hosting

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for npm)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Auth using the service-account JSON stored in GCP_SA_KEY
      # export_default_credentials makes firebase-tools pick it up automatically
      - name: Auth to Google (service account JSON)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      # Static deploy (no build step). Uses firebase.json/.firebaserc in the repo
      - name: Deploy static site to Firebase Hosting
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          set -e
          firebase use "$FIREBASE_PROJECT_ID" --token "" || true
          firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID" --non-interactive
